
// Old names:
// 
// This is another fun Microsoft special.
// They have an 'oldnames.lib' to remap a bunch of functions to versions,
// that start with an underscore:
// 
//     strdup -> _strdup
//     
// This is because, after C was standardized, they changed all of the unix/posix functions
// they had, but that did not make it into the C standard.
// To do this remapping (prefixing with an underscore) they use a library, which (of cause)
// ships with the compiler and not the ucrt.
// 
#pragma comment(linker, "/ALTERNATENAME:access=_access")
#pragma comment(linker, "/ALTERNATENAME:cabs=_cabs")
#pragma comment(linker, "/ALTERNATENAME:cgets=_cgets")
#pragma comment(linker, "/ALTERNATENAME:chdir=_chdir")
#pragma comment(linker, "/ALTERNATENAME:chmod=_chmod")
#pragma comment(linker, "/ALTERNATENAME:chsize=_chsize")
#pragma comment(linker, "/ALTERNATENAME:close=_close")
#pragma comment(linker, "/ALTERNATENAME:control87=_control87")
#pragma comment(linker, "/ALTERNATENAME:cprintf=_cprintf")
#pragma comment(linker, "/ALTERNATENAME:cputs=_cputs")
#pragma comment(linker, "/ALTERNATENAME:creat=_creat")
#pragma comment(linker, "/ALTERNATENAME:cscanf=_cscanf")
#pragma comment(linker, "/ALTERNATENAME:cwait=_cwait")
#pragma comment(linker, "/ALTERNATENAME:daylight=_daylight")
#pragma comment(linker, "/ALTERNATENAME:dup=_dup")
#pragma comment(linker, "/ALTERNATENAME:dup2=_dup2")
#pragma comment(linker, "/ALTERNATENAME:ecvt=_ecvt")
#pragma comment(linker, "/ALTERNATENAME:environ=_environ")
#pragma comment(linker, "/ALTERNATENAME:eof=_eof")
#pragma comment(linker, "/ALTERNATENAME:execl=_execl")
#pragma comment(linker, "/ALTERNATENAME:execle=_execle")
#pragma comment(linker, "/ALTERNATENAME:execlp=_execlp")
#pragma comment(linker, "/ALTERNATENAME:execlpe=_execlpe")
#pragma comment(linker, "/ALTERNATENAME:execv=_execv")
#pragma comment(linker, "/ALTERNATENAME:execve=_execve")
#pragma comment(linker, "/ALTERNATENAME:execvp=_execvp")
#pragma comment(linker, "/ALTERNATENAME:execvpe=_execvpe")
#pragma comment(linker, "/ALTERNATENAME:fcloseall=_fcloseall")
#pragma comment(linker, "/ALTERNATENAME:fcvt=_fcvt")
#pragma comment(linker, "/ALTERNATENAME:fdopen=_fdopen")
#pragma comment(linker, "/ALTERNATENAME:fgetchar=_fgetchar")
#pragma comment(linker, "/ALTERNATENAME:filelength=_filelength")
#pragma comment(linker, "/ALTERNATENAME:fileno=_fileno")
#pragma comment(linker, "/ALTERNATENAME:flushall=_flushall")
#pragma comment(linker, "/ALTERNATENAME:fpreset=_fpreset")
#pragma comment(linker, "/ALTERNATENAME:fputchar=_fputchar")
#pragma comment(linker, "/ALTERNATENAME:fstat=_fstat")
#pragma comment(linker, "/ALTERNATENAME:ftime=_ftime")
#pragma comment(linker, "/ALTERNATENAME:gcvt=_gcvt")
#pragma comment(linker, "/ALTERNATENAME:getch=_getch")
#pragma comment(linker, "/ALTERNATENAME:getche=_getche")
#pragma comment(linker, "/ALTERNATENAME:getcwd=_getcwd")
#pragma comment(linker, "/ALTERNATENAME:getpid=_getpid")
#pragma comment(linker, "/ALTERNATENAME:getw=_getw")
#pragma comment(linker, "/ALTERNATENAME:HUGE=_HUGE")
#pragma comment(linker, "/ALTERNATENAME:isatty=_isatty")
#pragma comment(linker, "/ALTERNATENAME:itoa=_itoa")
#pragma comment(linker, "/ALTERNATENAME:j0=_j0")
#pragma comment(linker, "/ALTERNATENAME:j1=_j1")
#pragma comment(linker, "/ALTERNATENAME:jn=_jn")
#pragma comment(linker, "/ALTERNATENAME:kbhit=_kbhit")
#pragma comment(linker, "/ALTERNATENAME:lfind=_lfind")
#pragma comment(linker, "/ALTERNATENAME:locking=_locking")
#pragma comment(linker, "/ALTERNATENAME:lsearch=_lsearch")
#pragma comment(linker, "/ALTERNATENAME:lseek=_lseek")
#pragma comment(linker, "/ALTERNATENAME:ltoa=_ltoa")
#pragma comment(linker, "/ALTERNATENAME:memccpy=_memccpy")
#pragma comment(linker, "/ALTERNATENAME:memicmp=_memicmp")
#pragma comment(linker, "/ALTERNATENAME:mkdir=_mkdir")
#pragma comment(linker, "/ALTERNATENAME:mktemp=_mktemp")
#pragma comment(linker, "/ALTERNATENAME:onexit=_onexit")
#pragma comment(linker, "/ALTERNATENAME:open=_open")
#pragma comment(linker, "/ALTERNATENAME:putch=_putch")
#pragma comment(linker, "/ALTERNATENAME:putenv=_putenv")
#pragma comment(linker, "/ALTERNATENAME:putw=_putw")
#pragma comment(linker, "/ALTERNATENAME:read=_read")
#pragma comment(linker, "/ALTERNATENAME:rmdir=_rmdir")
#pragma comment(linker, "/ALTERNATENAME:rmtmp=_rmtmp")
#pragma comment(linker, "/ALTERNATENAME:setmode=_setmode")
#pragma comment(linker, "/ALTERNATENAME:sopen=_sopen")
#pragma comment(linker, "/ALTERNATENAME:spawnl=_spawnl")
#pragma comment(linker, "/ALTERNATENAME:spawnle=_spawnle")
#pragma comment(linker, "/ALTERNATENAME:spawnlp=_spawnlp")
#pragma comment(linker, "/ALTERNATENAME:spawnlpe=_spawnlpe")
#pragma comment(linker, "/ALTERNATENAME:spawnv=_spawnv")
#pragma comment(linker, "/ALTERNATENAME:spawnve=_spawnve")
#pragma comment(linker, "/ALTERNATENAME:spawnvp=_spawnvp")
#pragma comment(linker, "/ALTERNATENAME:spawnvpe=_spawnvpe")
#pragma comment(linker, "/ALTERNATENAME:stat=_stat")
#pragma comment(linker, "/ALTERNATENAME:strcmpi=_strcmpi")
#pragma comment(linker, "/ALTERNATENAME:strdup=_strdup")
#pragma comment(linker, "/ALTERNATENAME:stricmp=_stricmp")
#pragma comment(linker, "/ALTERNATENAME:strlwr=_strlwr")
#pragma comment(linker, "/ALTERNATENAME:strnicmp=_strnicmp")
#pragma comment(linker, "/ALTERNATENAME:strnset=_strnset")
#pragma comment(linker, "/ALTERNATENAME:strrev=_strrev")
#pragma comment(linker, "/ALTERNATENAME:strset=_strset")
#pragma comment(linker, "/ALTERNATENAME:strupr=_strupr")
#pragma comment(linker, "/ALTERNATENAME:swab=_swab")
#pragma comment(linker, "/ALTERNATENAME:sys_errlist=_sys_errlist")
#pragma comment(linker, "/ALTERNATENAME:sys_nerr=_sys_nerr")
#pragma comment(linker, "/ALTERNATENAME:tell=_tell")
#pragma comment(linker, "/ALTERNATENAME:tempnam=_tempnam")
#pragma comment(linker, "/ALTERNATENAME:timezone=_timezone")
#pragma comment(linker, "/ALTERNATENAME:tzname=_tzname")
#pragma comment(linker, "/ALTERNATENAME:tzset=_tzset")
#pragma comment(linker, "/ALTERNATENAME:ultoa=_ultoa")
#pragma comment(linker, "/ALTERNATENAME:umask=_umask")
#pragma comment(linker, "/ALTERNATENAME:ungetch=_ungetch")
#pragma comment(linker, "/ALTERNATENAME:unlink=_unlink")
#pragma comment(linker, "/ALTERNATENAME:utime=_utime")
#pragma comment(linker, "/ALTERNATENAME:wcsdup=_wcsdup")
#pragma comment(linker, "/ALTERNATENAME:wcsicmp=_wcsicmp")
#pragma comment(linker, "/ALTERNATENAME:wcsicoll=_wcsicoll")
#pragma comment(linker, "/ALTERNATENAME:wcslwr=_wcslwr")
#pragma comment(linker, "/ALTERNATENAME:wcsnicmp=_wcsnicmp")
#pragma comment(linker, "/ALTERNATENAME:wcsnset=_wcsnset")
#pragma comment(linker, "/ALTERNATENAME:wcsrev=_wcsrev")
#pragma comment(linker, "/ALTERNATENAME:wcsset=_wcsset")
#pragma comment(linker, "/ALTERNATENAME:wcsupr=_wcsupr")
#pragma comment(linker, "/ALTERNATENAME:write=_write")
#pragma comment(linker, "/ALTERNATENAME:y0=_y0")
#pragma comment(linker, "/ALTERNATENAME:y1=_y1")
#pragma comment(linker, "/ALTERNATENAME:yn=_yn")

